name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        echo "test"
        node -v
      env:
        CI: true
